steps {
  requested_information {
    key: "xid"
    value: "264145324"
  }
}
steps {
  requested_information {
    key: "model_url"
    value: "evergreen://blade:gdm-aip-fastpath-agent-generate-service-prod/lmroot-v3-uniserve:/search-hosted-servers-models/gemini-v3p1m-or-rev19-128k"
  }
}
