apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-data
  namespace: paperclip
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-fuse
  resources:
    requests:
      storage: 10Gi
