apiVersion: v1
kind: Secret
metadata:
  name: paperclip-db
  namespace: paperclip
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:uW3qQ%3C%28Jpo9%2F%5Dq%403Os%5D%7CQP%7C5@10.10.10.63:5432/postgres-paperclp?sslmode=prefer"
